name: Workflow for python
on:
  push:
    branches:
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: install python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: linter
      uses: sunnysid3up/python-linter@master
      with:
        source: .
        strict: "medium"
        mypy-options: ""
        pylint-options: ""
        isort-options: ""
        django: false
    - name: manual approval
      uses: trstringer/manual-approval@v1
      with:
        secret: ${{ github.TOKEN }}
        approvers: heloise-viegas  
        minimum-approvals: 1
        issue-title: "Check code before deployment"
    - name: run code
      run: python Hello.py

